package is.hi.hbv401g.team1h.utils;

import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.sqlobject.SqlObjectPlugin;

public class JdbiManager {
    private static final String URL = "jdbc:sqlite:src/main/resources/datbs.sqlite";
    private static volatile Jdbi jdbiInstance;

    private JdbiManager() {}

    public static Jdbi getInstance() {
        if (jdbiInstance == null) {
            synchronized (JdbiManager.class) {
                if (jdbiInstance == null) {
                    jdbiInstance = Jdbi.create(URL);
                    jdbiInstance.installPlugin(new SqlObjectPlugin());

                    instantiate();
                }
            }
        }
        return jdbiInstance;
    }


     public static void populate(Jdbi jdbi) {
        jdbi.useHandle(handle -> {
            handle.execute("""
                        INSERT INTO amenities (amenity_name) VALUES
                                                                 ('Free Wi-Fi'),
                                                                 ('Parking'),
                                                                 ('24-Hour Front Desk'),
                                                                 ('Fitness Center'),
                                                                 ('Swimming Pool'),
                                                                 ('Spa & Wellness Center'),
                                                                 ('Airport Shuttle'),
                                                                 ('Room Service'),
                                                                 ('Restaurant'),
                                                                 ('Bar'),
                                                                 ('Laundry Service'),
                                                                 ('Non-Smoking Rooms'),
                                                                 ('Pet-Friendly'),
                                                                 ('Business Center'),
                                                                 ('Air Conditioning'),
                                                                 ('Heating'),
                                                                 ('Flat-Screen TV'),
                                                                 ('Mini-Bar'),
                                                                 ('Safe Deposit Box'),
                                                                 ('Concierge Service');
                    """);

            handle.execute("""
                        INSERT INTO hotels (hotel_name, hotel_address, hotel_city, star_rating, description)
                        VALUES ('Hotel Búðir', 'Sæbraut 136', 'Borgarnes', 4.5, 'Experience Icelandic hospitality.'),
                               ('Ion Adventure Hotel', 'Hverfisgata 51', 'Vestmannaeyjar', 0.5, 'Close to popular attractions.'),
                               ('Black Pearl Suites', 'Laugavegur 142', 'Reykjavík', 1.5, 'Cozy retreat with beautiful views.'),
                               ('Hotel Borg', 'Frakkastígur 120', 'Egilsstaðir', 0.5, 'Modern design with Icelandic charm.'),
                               ('Fosshotel Glacier', 'Öldugata 50', 'Húsavík', 2.5, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Silica Hotel', 'Miðtún 11', 'Akranes', 3.5, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Hotel Grímsborgir', 'Thingholtstræti 2', 'Borgarnes', 0.0, 'A short walk to museums and restaurants.'),
                               ('Alda Hotel', 'Ránargata 130', 'Akureyri', 4.5, 'Family-friendly and near local shops.'),
                               ('Sandhotel', 'Sólvellir 139', 'Akureyri', 5.0, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Hotel Rangá', 'Lindargata 46', 'Ísafjörður', 0.0, 'Experience Icelandic hospitality.'),
                               ('Kvosin Downtown Hotel', 'Skólavörðustígur 51', 'Keflavík', 2.0, 'Cozy retreat with beautiful views.'),
                               ('Hotel Kea', 'Lækurvegur 70', 'Húsavík', 4.5, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Skuggi Hotel', 'Öldugata 71', 'Akureyri', 1.0, 'Rustic charm and modern amenities.'),
                               ('Reykjavik Residence', 'Lindargata 53', 'Egilsstaðir', 1.0, 'Experience Icelandic hospitality.'),
                               ('Grand Hotel Reykjavik', 'Barónsstígur 50', 'Egilsstaðir', 0.5, 'A short walk to museums and restaurants.'),
                               ('Hotel Holt', 'Sæbraut 145', 'Keflavík', 1.0, 'A perfect stopover for ring road travelers.'),
                               ('Hotel Fron', 'Barónsstígur 58', 'Akranes', 0.0, 'Experience Icelandic hospitality.'),
                               ('Center Hotel Plaza', 'Aðalgata 32', 'Selfoss', 3.0, 'Cozy retreat with beautiful views.'),
                               ('Hotel Vík í Mýrdal', 'Thingholtstræti 63', 'Ísafjörður', 3.5, 'Family-friendly and near local shops.'),
                               ('Akureyri Backpackers', 'Skólavörðustígur 52', 'Reykjavík', 3.5, 'A perfect stopover for ring road travelers.'),
                               ('Gistiheimilið Mýrar', 'Thingholtstræti 88', 'Selfoss', 3.5, 'A perfect stopover for ring road travelers.'),
                               ('Siglo Hotel', 'Hverfisgata 144', 'Egilsstaðir', 1.5, 'Family-friendly and near local shops.'),
                               ('Hotel Kría', 'Miðtún 89', 'Húsavík', 2.0, 'A short walk to museums and restaurants.'),
                               ('Grandi by Center Hotels', 'Ránargata 71', 'Vestmannaeyjar', 4.0, 'Close to popular attractions.'),
                               ('Apotek Hotel', 'Hafnargata 74', 'Ísafjörður', 2.0, 'Family-friendly and near local shops.'),
                               ('Rey Apartments', 'Hafnargata 120', 'Egilsstaðir', 2.0, 'Modern design with Icelandic charm.'),
                               ('Fosshotel Húsavík', 'Borgartún 88', 'Selfoss', 1.0, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Hotel Varmahlíð', 'Eyrarvegur 84', 'Keflavík', 1.5, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Blábjörg Resort', 'Lindargata 120', 'Akureyri', 5.0, 'Close to popular attractions.'),
                               ('Hali Country Hotel', 'Goðabraut 91', 'Húsavík', 3.0, 'Family-friendly and near local shops.'),
                               ('Berjaya Hérað', 'Miðtún 143', 'Akureyri', 5.0, 'Experience Icelandic hospitality.'),
                               ('Eyja Guldsmeden Hotel', 'Sólvellir 86', 'Egilsstaðir', 0.0, 'Rustic charm and modern amenities.'),
                               ('Storm Hotel', 'Miðtún 135', 'Borgarnes', 5.0, 'Cozy retreat with beautiful views.'),
                               ('Northern Comfort Apartments', 'Lækurvegur 39', 'Ísafjörður', 2.5,
                                'A perfect stopover for ring road travelers.'),
                               ('Hotel Edda', 'Hverfisgata 38', 'Egilsstaðir', 4.5, 'Family-friendly and near local shops.'),
                               ('Umi Hotel', 'Hafnarstræti 35', 'Keflavík', 2.0, 'A perfect stopover for ring road travelers.'),
                               ('Midgard Base Camp', 'Miðtún 136', 'Vestmannaeyjar', 1.0, 'Experience Icelandic hospitality.'),
                               ('Guesthouse Sunna', 'Eyrarvegur 92', 'Húsavík', 4.5, 'Family-friendly and near local shops.'),
                               ('Hotel Selfoss', 'Sólvellir 112', 'Akranes', 0.0, 'Cozy retreat with beautiful views.'),
                               ('Guesthouse Flúðir', 'Lindargata 125', 'Vestmannaeyjar', 2.0, 'Rustic charm and modern amenities.'),
                               ('Icelandic Airwaves Inn', 'Eyrarvegur 20', 'Akranes', 4.5, 'Experience Icelandic hospitality.'),
                               ('Geysir Green Hotel', 'Thingholtstræti 117', 'Ísafjörður', 5.0, 'Modern design with Icelandic charm.'),
                               ('LavaField Lodge', 'Sæbraut 107', 'Vestmannaeyjar', 3.0, 'Close to popular attractions.'),
                               ('Aurora Dream Hotel', 'Ránargata 91', 'Húsavík', 4.5, 'Family-friendly and near local shops.'),
                               ('Saga & Splendor Retreat', 'Goðabraut 66', 'Húsavík', 1.5, 'Cozy retreat with beautiful views.'),
                               ('Hrafninn Guesthouse', 'Sæbraut 61', 'Reykjavík', 0.0, 'Close to popular attractions.'),
                               ('Frost and Fire Boutique', 'Thingholtstræti 100', 'Egilsstaðir', 5.0, 'Experience Icelandic hospitality.'),
                               ('Skálafell Lodge', 'Ránargata 148', 'Akureyri', 2.5, 'A perfect stopover for ring road travelers.'),
                               ('Þingholt Stay', 'Barónsstígur 23', 'Reykjavík', 2.0, 'Modern design with Icelandic charm.'),
                               ('Arnarhvoll Hotel', 'Skólavörðustígur 4', 'Selfoss', 5.0, 'A perfect stopover for ring road travelers.'),
                               ('Freya''s Rest Hotel', 'Hafnargata 12', 'Borgarnes', 3.5, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Hotel Kalda Lyng', 'Frakkastígur 141', 'Reykjavík', 0.0, 'A perfect stopover for ring road travelers.'),
                               ('Blue Lagoon Retreat', 'Frakkastígur 107', 'Vestmannaeyjar', 1.0, 'Close to popular attractions.'),
                               ('Whale Watch Inn', 'Miðtún 13', 'Akranes', 2.0, 'Close to popular attractions.'),
                               ('GeoHotel Grindavík', 'Laugavegur 5', 'Selfoss', 2.0, 'Modern design with Icelandic charm.'),
                               ('Golden Circle Resort', 'Öldugata 55', 'Akureyri', 5.0, 'Cozy retreat with beautiful views.'),
                               ('Fire & Ice Hotel', 'Frakkastígur 65', 'Keflavík', 0.0, 'Enjoy the Northern Lights from our rooftop.'),
                               ('Moss View Hotel', 'Öldugata 26', 'Akranes', 2.0, 'Breathtaking views of mountains and fjords.'),
                               ('Sea Breeze Guesthouse', 'Frakkastígur 1', 'Egilsstaðir', 3.5, 'Experience Icelandic hospitality.'),
                               ('Borealis Basecamp', 'Frakkastígur 135', 'Keflavík', 4.0, 'Close to popular attractions.'),
                               ('Laugascape Hotel', 'Thingholtstræti 118', 'Keflavík', 0.0, 'Experience Icelandic hospitality.'),
                               ('Nordic Light Inn', 'Öldugata 88', 'Reykjavík', 2.5, 'A short walk to museums and restaurants.'),
                               ('Eldey Island Retreat', 'Hafnargata 73', 'Akranes', 5.0, 'A short walk to museums and restaurants.'),
                               ('Bright Aurora Lodging', 'Skólavörðustígur 148', 'Egilsstaðir', 3.0, 'Family-friendly and near local shops.'),
                               ('Þórsmörk Trails Hotel', 'Lindargata 95', 'Ísafjörður', 4.0, 'A perfect stopover for ring road travelers.'),
                               ('Frysta Guesthouse', 'Skólavörðustígur 115', 'Selfoss', 5.0, 'Cozy retreat with beautiful views.'),
                               ('Eldfell Hotel', 'Goðabraut 33', 'Húsavík', 4.5, 'Breathtaking views of mountains and fjords.'),
                               ('Hotel Berg', 'Miðtún 4', 'Ísafjörður', 2.5, 'Rustic charm and modern amenities.'),
                               ('Northern Saga Inn', 'Lindargata 87', 'Ísafjörður', 2.5, 'Close to popular attractions.'),
                               ('Torfhús Retreat', 'Ránargata 131', 'Borgarnes', 4.5, 'Close to popular attractions.'),
                               ('Hotel Laugarbakki', 'Aðalgata 43', 'Selfoss', 4.5, 'Breathtaking views of mountains and fjords.'),
                               ('Vatnsholt Lodge', 'Thingholtstræti 47', 'Selfoss', 2.5, 'Close to popular attractions.'),
                               ('Old Post Office Guesthouse', 'Sæbraut 33', 'Keflavík', 4.0, 'A short walk to museums and restaurants.'),
                               ('Hótel Laugar', 'Skólavörðustígur 55', 'Keflavík', 3.0, 'Modern design with Icelandic charm.'),
                               ('Fosshotel Stykkishólmur', 'Lækurvegur 95', 'Reykjavík', 4.0, 'Breathtaking views of mountains and fjords.'),
                               ('Hotel Egilsen', 'Sólvellir 32', 'Egilsstaðir', 0.5, 'Family-friendly and near local shops.'),
                               ('Grundarfjörður Apartments', 'Miðtún 35', 'Akureyri', 4.0, 'A short walk to museums and restaurants.'),
                               ('Fosshotel Reykholt', 'Öldugata 28', 'Vestmannaeyjar', 0.0, 'Experience Icelandic hospitality.'),
                               ('Hotel Edda ML Laugarvatn', 'Sólvellir 60', 'Keflavík', 5.0, 'Experience Icelandic hospitality.'),
                               ('Seljavallalaug Lodge', 'Aðalgata 88', 'Egilsstaðir', 4.0, 'Rustic charm and modern amenities.'),
                               ('Black Sand Beach Hotel', 'Sólvellir 56', 'Ísafjörður', 5.0, 'Family-friendly and near local shops.'),
                               ('Eldish Resort', 'Kirkjutorg 23', 'Selfoss', 5.0, 'Modern design with Icelandic charm.'),
                               ('Fagradalsfjall Inn', 'Hafnargata 40', 'Keflavík', 3.5, 'Rustic charm and modern amenities.'),
                               ('Krystol Lights Hotel', 'Kirkjutorg 74', 'Egilsstaðir', 1.5, 'Modern design with Icelandic charm.'),
                               ('The Nest Guesthouse', 'Hafnargata 102', 'Selfoss', 4.5, 'Experience Icelandic hospitality.'),
                               ('Arctic Jewel Hotel', 'Eyrarvegur 50', 'Keflavík', 4.0, 'Modern design with Icelandic charm.'),
                               ('Cool Lava Hotel', 'Borgartún 102', 'Borgarnes', 3.0, 'Close to popular attractions.'),
                               ('Geysir Aurora Inn', 'Barónsstígur 62', 'Borgarnes', 3.0, 'Family-friendly and near local shops.'),
                               ('Sea Cliff Guesthouse', 'Borgartún 123', 'Reykjavík', 2.5, 'Close to popular attractions.'),
                               ('Ísafjörður Harbour Hotel', 'Borgartún 113', 'Vestmannaeyjar', 3.0, 'Modern design with Icelandic charm.'),
                               ('Hótel Ísland', 'Hafnarstræti 150', 'Akranes', 3.0, 'A short walk to museums and restaurants.'),
                               ('Grand Aurora Suites', 'Kirkjutorg 42', 'Borgarnes', 5.0, 'Breathtaking views of mountains and fjords.'),
                               ('Viking Lodge', 'Frakkastígur 147', 'Egilsstaðir', 0.0, 'Modern design with Icelandic charm.'),
                               ('Hotel Álfheimar', 'Öldugata 84', 'Akureyri', 2.0, 'Family-friendly and near local shops.'),
                               ('Northern Pearl Hotel', 'Thingholtstræti 11', 'Vestmannaeyjar', 5.0, 'Close to popular attractions.'),
                               ('Glacier Guesthouse', 'Goðabraut 33', 'Vestmannaeyjar', 2.0, 'Modern design with Icelandic charm.'),
                               ('Valhalla Comfort Hotel', 'Sæbraut 55', 'Húsavík', 2.5, 'Family-friendly and near local shops.'),
                               ('Hotel Hekla', 'Barónsstígur 69', 'Keflavík', 3.5, 'Breathtaking views of mountains and fjords.'),
                               ('Silfra Sojourn Hotel', 'Öldugata 108', 'Vestmannaeyjar', 3.0, 'Rustic charm and modern amenities.'),
                               ('GreenKey Retreat', 'Sæbraut 124', 'Akranes', 0.0, 'Cozy retreat with beautiful views.');
            """);

            handle.execute("""
                INSERT INTO hotel_amenities (hotel_id, amenity_id) VALUES
                                                                       (1, 13),
                                                                       (1, 11),
                                                                       (1, 4),
                                                                       (1, 18),
                                                                       (1, 2),
                                                                       (1, 3),
                                                                       (1, 20),
                                                                       (2, 5),
                                                                       (2, 19),
                                                                       (2, 7),
                                                                       (2, 9),
                                                                       (2, 17),
                                                                       (2, 10),
                                                                       (3, 12),
                                                                       (3, 8),
                                                                       (3, 13),
                                                                       (3, 3),
                                                                       (4, 1),
                                                                       (4, 7),
                                                                       (4, 10),
                                                                       (4, 3),
                                                                       (4, 2),
                                                                       (4, 8),
                                                                       (5, 10),
                                                                       (5, 19),
                                                                       (5, 3),
                                                                       (5, 15),
                                                                       (5, 17),
                                                                       (6, 6),
                                                                       (6, 13),
                                                                       (6, 3),
                                                                       (6, 14),
                                                                       (6, 10),
                                                                       (6, 12),
                                                                       (6, 16),
                                                                       (6, 9),
                                                                       (7, 20),
                                                                       (7, 4),
                                                                       (7, 7),
                                                                       (7, 6),
                                                                       (7, 14),
                                                                       (7, 9),
                                                                       (7, 8),
                                                                       (7, 18),
                                                                       (8, 5),
                                                                       (8, 16),
                                                                       (8, 2),
                                                                       (8, 6),
                                                                       (8, 12),
                                                                       (8, 17),
                                                                       (8, 9),
                                                                       (9, 17),
                                                                       (9, 18),
                                                                       (9, 12),
                                                                       (9, 2),
                                                                       (9, 1),
                                                                       (9, 10),
                                                                       (10, 2),
                                                                       (10, 1),
                                                                       (10, 16),
                                                                       (11, 14),
                                                                       (11, 7),
                                                                       (11, 6),
                                                                       (11, 8),
                                                                       (11, 12),
                                                                       (11, 19),
                                                                       (11, 15),
                                                                       (12, 11),
                                                                       (12, 4),
                                                                       (12, 1),
                                                                       (12, 5),
                                                                       (13, 10),
                                                                       (14, 3),
                                                                       (15, 5),
                                                                       (15, 20),
                                                                       (15, 11),
                                                                       (15, 9),
                                                                       (15, 2),
                                                                       (15, 17),
                                                                       (16, 8),
                                                                       (16, 3),
                                                                       (16, 16),
                                                                       (16, 13),
                                                                       (16, 19),
                                                                       (17, 6),
                                                                       (17, 14),
                                                                       (17, 7),
                                                                       (17, 9),
                                                                       (17, 4),
                                                                       (17, 2),
                                                                       (18, 12),
                                                                       (18, 18),
                                                                       (18, 7),
                                                                       (18, 6),
                                                                       (19, 1),
                                                                       (19, 15),
                                                                       (19, 17),
                                                                       (19, 10),
                                                                       (19, 14),
                                                                       (20, 11),
                                                                       (20, 5),
                                                                       (20, 13),
                                                                       (20, 4),
                                                                       (20, 19),
                                                                       (21, 3),
                                                                       (21, 9),
                                                                       (21, 8),
                                                                       (21, 6),
                                                                       (21, 20),
                                                                       (21, 2),
                                                                       (22, 1),
                                                                       (22, 10),
                                                                       (23, 12),
                                                                       (23, 6),
                                                                       (23, 5),
                                                                       (23, 14),
                                                                       (23, 20),
                                                                       (24, 8),
                                                                       (24, 17),
                                                                       (24, 2),
                                                                       (24, 3),
                                                                       (24, 11),
                                                                       (24, 13),
                                                                       (25, 6),
                                                                       (25, 4),
                                                                       (25, 9),
                                                                       (25, 10),
                                                                       (25, 18),
                                                                       (26, 19),
                                                                       (26, 1),
                                                                       (26, 2),
                                                                       (26, 13),
                                                                       (26, 17),
                                                                       (27, 3),
                                                                       (27, 6),
                                                                       (27, 12),
                                                                       (27, 20),
                                                                       (27, 10),
                                                                       (28, 1),
                                                                       (28, 5),
                                                                       (28, 14),
                                                                       (28, 4),
                                                                       (28, 11),
                                                                       (29, 2),
                                                                       (29, 6),
                                                                       (29, 8),
                                                                       (29, 18),
                                                                       (30, 9),
                                                                       (30, 3),
                                                                       (30, 1),
                                                                       (30, 16),
                                                                       (30, 13),
                                                                       (31, 19),
                                                                       (31, 7),
                                                                       (31, 2),
                                                                       (31, 14),
                                                                       (32, 5),
                                                                       (32, 11),
                                                                       (32, 9),
                                                                       (32, 16),
                                                                       (32, 1),
                                                                       (33, 6),
                                                                       (33, 3),
                                                                       (33, 17),
                                                                       (33, 15),
                                                                       (33, 8),
                                                                       (34, 13),
                                                                       (34, 14),
                                                                       (34, 4),
                                                                       (34, 12),
                                                                       (34, 19),
                                                                       (34, 10),
                                                                       (35, 9),
                                                                       (35, 20),
                                                                       (35, 6),
                                                                       (35, 8),
                                                                       (35, 1),
                                                                       (35, 13),
                                                                       (36, 4),
                                                                       (36, 2),
                                                                       (36, 11),
                                                                       (36, 16),
                                                                       (36, 3),
                                                                       (36, 18),
                                                                       (37, 7),
                                                                       (37, 12),
                                                                       (37, 5),
                                                                       (37, 10),
                                                                       (37, 14),
                                                                       (38, 15),
                                                                       (38, 6),
                                                                       (38, 17),
                                                                       (38, 8),
                                                                       (38, 2),
                                                                       (39, 3),
                                                                       (39, 13),
                                                                       (39, 4),
                                                                       (39, 7),
                                                                       (39, 20),
                                                                       (39, 12),
                                                                       (40, 1),
                                                                       (40, 5),
                                                                       (40, 9),
                                                                       (40, 18),
                                                                       (40, 14),
                                                                       (41, 11),
                                                                       (41, 19),
                                                                       (41, 6),
                                                                       (41, 17),
                                                                       (41, 3),
                                                                       (42, 16),
                                                                       (42, 4),
                                                                       (42, 13),
                                                                       (42, 7),
                                                                       (42, 15),
                                                                       (43, 8),
                                                                       (43, 5),
                                                                       (43, 2),
                                                                       (43, 12),
                                                                       (43, 9),
                                                                       (44, 6),
                                                                       (44, 10),
                                                                       (44, 14),
                                                                       (44, 11),
                                                                       (45, 1),
                                                                       (45, 3),
                                                                       (45, 17),
                                                                       (45, 19),
                                                                       (46, 7),
                                                                       (46, 16),
                                                                       (46, 2),
                                                                       (46, 20),
                                                                       (47, 8),
                                                                       (47, 14),
                                                                       (47, 18),
                                                                       (47, 6),
                                                                       (47, 13),
                                                                       (48, 4),
                                                                       (48, 5),
                                                                       (48, 10),
                                                                       (48, 1),
                                                                       (48, 20),
                                                                       (49, 3),
                                                                       (49, 7),
                                                                       (49, 2),
                                                                       (49, 15),
                                                                       (50, 9),
                                                                       (50, 12),
                                                                       (50, 11),
                                                                       (50, 16),
                                                                       (50, 17),
                                                                       (50, 19),
                                                                       (51, 6),
                                                                       (51, 8),
                                                                       (51, 13),
                                                                       (51, 14),
                                                                       (51, 4),
                                                                       (52, 5),
                                                                       (52, 18),
                                                                       (52, 3),
                                                                       (52, 7),
                                                                       (52, 20),
                                                                       (53, 1),
                                                                       (53, 2),
                                                                       (53, 9),
                                                                       (53, 10),
                                                                       (53, 12),
                                                                       (54, 16),
                                                                       (54, 11),
                                                                       (54, 15),
                                                                       (54, 17),
                                                                       (54, 19),
                                                                       (55, 2),
                                                                       (55, 3),
                                                                       (55, 13),
                                                                       (55, 6),
                                                                       (55, 8),
                                                                       (56, 14),
                                                                       (56, 9),
                                                                       (56, 18),
                                                                       (56, 12),
                                                                       (56, 4),
                                                                       (57, 1),
                                                                       (57, 5),
                                                                       (57, 20),
                                                                       (57, 7),
                                                                       (58, 10),
                                                                       (58, 11),
                                                                       (58, 15),
                                                                       (58, 19),
                                                                       (59, 16),
                                                                       (59, 17),
                                                                       (60, 6),
                                                                       (60, 8),
                                                                       (60, 3),
                                                                       (60, 13),
                                                                       (60, 18),
                                                                       (61, 4),
                                                                       (61, 14),
                                                                       (61, 9),
                                                                       (61, 7),
                                                                       (61, 11),
                                                                       (62, 2),
                                                                       (62, 10),
                                                                       (62, 5),
                                                                       (62, 15),
                                                                       (62, 20),
                                                                       (63, 16),
                                                                       (63, 1),
                                                                       (63, 12),
                                                                       (63, 19),
                                                                       (64, 17),
                                                                       (65, 3),\s
                                                                       (65, 19),\s
                                                                       (65, 6),\s
                                                                       (65, 18),\s
                                                                       (65, 11),\s
                                                                       (65, 17),\s
                                                                       (65, 10), (65, 13),
                                                                       (66, 14), (66, 19), (66, 7), (66, 9), (66, 6),
                                                                       (67, 16), (67, 5), (67, 18), (67, 6), (67, 3), (67, 1), (67, 12),
                                                                       (68, 4), (68, 13), (68, 6), (68, 15), (68, 2), (68, 16), (68, 5), (68, 18),
                                                                       (69, 14), (69, 3), (69, 16), (69, 15), (69, 7),
                                                                       (70, 19), (70, 4), (70, 12), (70, 9),
                                                                       (71, 11), (71, 20), (71, 8), (71, 17), (71, 15),
                                                                       (72, 10), (72, 5), (72, 11), (72, 19), (72, 17), (72, 9), (72, 20), (72, 3),
                                                                       (73, 18), (73, 1), (73, 4), (73, 2), (73, 19), (73, 15), (73, 11),
                                                                       (74, 3), (74, 8), (74, 7), (74, 11), (74, 15), (74, 4), (74, 1),
                                                                       (75, 8), (75, 14), (75, 16), (75, 13), (75, 11), (75, 10),
                                                                       (76, 17), (76, 7), (76, 12), (76, 15), (76, 20),
                                                                       (77, 7), (77, 10), (77, 3), (77, 4), (77, 14), (77, 13), (77, 17),
                                                                       (78, 11), (78, 8), (78, 15), (78, 14), (78, 9), (78, 18), (78, 13),
                                                                       (79, 13), (79, 4), (79, 11), (79, 10), (79, 15), (79, 18), (79, 1), (79, 3),
                                                                       (80, 20), (80, 14), (80, 8), (80, 12), (80, 19),
                                                                       (81, 6), (81, 13), (81, 18), (81, 2), (81, 15), (81, 10), (81, 4),
                                                                       (82, 5), (82, 11), (82, 7), (82, 9), (82, 17),
                                                                       (83, 3), (83, 12), (83, 1), (83, 14), (83, 20), (83, 16),
                                                                       (84, 2), (84, 4), (84, 6), (84, 19), (84, 13), (84, 17),
                                                                       (85, 9), (85, 11), (85, 10), (85, 5), (85, 3),
                                                                       (86, 8), (86, 18), (86, 15), (86, 6), (86, 7), (86, 14),
                                                                       (87, 1), (87, 2), (87, 12), (87, 16), (87, 20), (87, 13),
                                                                       (88, 11), (88, 10), (88, 17), (88, 8), (88, 4),
                                                                       (89, 5), (89, 6), (89, 9), (89, 3), (89, 7), (89, 1), (89, 19),
                                                                       (90, 14), (90, 2), (90, 16), (90, 13), (90, 18), (90, 15),
                                                                       (91, 2),
                                                                       (91, 6),
                                                                       (91, 8),
                                                                       (91, 13),
                                                                       (91, 20),
                                                                       (92, 4),
                                                                       (92, 10),
                                                                       (92, 15),
                                                                       (92, 19),
                                                                       (93, 5),
                                                                       (93, 11),
                                                                       (93, 1),
                                                                       (93, 17),
                                                                       (94, 3),
                                                                       (94, 7),
                                                                       (94, 14),
                                                                       (94, 16),
                                                                       (95, 9),
                                                                       (95, 12),
                                                                       (95, 18),
                                                                       (96, 1),
                                                                       (96, 6),
                                                                       (96, 13),
                                                                       (96, 19),
                                                                       (96, 8),
                                                                       (97, 4),
                                                                       (97, 10),
                                                                       (97, 14),
                                                                       (97, 17),
                                                                       (98, 2),
                                                                       (98, 5),
                                                                       (98, 11),
                                                                       (98, 16),
                                                                       (98, 20),
                                                                       (99, 3),
                                                                       (99, 7),
                                                                       (99, 9),
                                                                       (99, 12),
                                                                       (100, 15),
                                                                       (100, 18);
            """);
        });
    }

    private static void instantiate() {
        jdbiInstance.useHandle(handle -> {
            handle.execute("""
            
                CREATE TABLE IF NOT EXISTS hotels (
                    hotel_id        INTEGER PRIMARY KEY AUTOINCREMENT,
                    hotel_name      TEXT NOT NULL,
                    hotel_address   TEXT NOT NULL,
                    hotel_city      TEXT NOT NULL,
                    star_rating     DOUBLE CHECK ( star_rating BETWEEN 0.0 AND 5.0),
                    description     TEXT
            )     
                
            """);

            handle.execute("""
            
                CREATE TABLE IF NOT EXISTS rooms (
                    room_id         INTEGER PRIMARY KEY AUTOINCREMENT,
                    hotel_id        INTEGER NOT NULL,
                    room_number     TEXT,
                    room_price_per_night INTEGER NOT NULL,
                
                    FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id)
            )
            
            """);

            handle.execute("""
                
                CREATE TABLE IF NOT EXISTS amenities (
                    amenity_id      INTEGER PRIMARY KEY AUTOINCREMENT,
                    amenity_name    TEXT NOT NULL UNIQUE
                )
            
            """);

            handle.execute("""
            
                CREATE TABLE IF NOT EXISTS hotel_amenities (
                    hotel_id        INTEGER NOT NULL,
                    amenity_id      INTEGER NOT NULL,
                
                    PRIMARY KEY (hotel_id, amenity_id),
                
                    FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE,
                    FOREIGN KEY (amenity_id) REFERENCES amenities(amenity_id) ON DELETE CASCADE
                )
            
            """);

            handle.execute("""
            
                CREATE TABLE IF NOT EXISTS bookings (
                    booking_id 		INTEGER PRIMARY KEY AUTOINCREMENT,
                    room_id			INTEGER NOT NULL,
                    from_date		TEXT NOT NULL,
                    to_date			TEXT NOT NULL,
                    total_price		INTEGER NOT NULL,
                
                    FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE
                )
            
            """);
        });
    }
}
